/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ru.kunakbaev.databaseeditormaven.frame;

import ru.kunakbaev.databaseeditormaven.DataBaseEditorMaven;
import ru.kunakbaev.databaseeditormaven.configuration.PosgresConection;
import ru.kunakbaev.databaseeditormaven.controller.MainFrameController;
import ru.kunakbaev.databaseeditormaven.service.DatabaseService;
import ru.kunakbaev.databaseeditormaven.service.ui.TreeService;

/**
 *
 * @author HPPavilion
 */
public class MainFrame extends javax.swing.JFrame {

    private final MainFrameController mainFrameController;
    
    public MainFrame(MainFrameController mainFrameController) {
        this.mainFrameController = mainFrameController;

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbTreeScrollPanel = new javax.swing.JScrollPane();
        dbTree = new javax.swing.JTree();
        updateTreeButton = new javax.swing.JButton();
        uppMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        dbTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        dbTreeScrollPanel.setViewportView(dbTree);

        updateTreeButton.setText("Update tree");
        updateTreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTreeButtonActionPerformed(evt);
            }
        });

        uppMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("File");
        uppMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        uppMenuBar.add(jMenu2);

        setJMenuBar(uppMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbTreeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateTreeButton)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateTreeButton)
                        .addGap(0, 292, Short.MAX_VALUE))
                    .addComponent(dbTreeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateTreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTreeButtonActionPerformed
        dbTree.setModel(mainFrameController.getTreeModel());
        dbTree.updateUI();
    }//GEN-LAST:event_updateTreeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    PosgresConection posgresConection = new PosgresConection();

                    var conn = posgresConection.dataSource();

                    DatabaseService databaseService = new DatabaseService(conn);
                    TreeService treeService = new TreeService(databaseService);
                    MainFrameController mainFrameController = new MainFrameController(treeService);

                    new MainFrame(mainFrameController).setVisible(true);


                } catch (Exception e) {

                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree dbTree;
    private javax.swing.JScrollPane dbTreeScrollPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton updateTreeButton;
    private javax.swing.JMenuBar uppMenuBar;
    // End of variables declaration//GEN-END:variables
}
